/* ── Словарь перевода интерфейса документации ──
 * Англоязычные тексты в docs-* файлах (заголовки разделов, описания API,
 * подписи кнопок) переводятся на русский при рендере. Точное совпадение
 * строки; не найденные в словаре строки остаются как есть.
 */
export const RU: Record<string, string> = {
  // Общие метки
  'Guide': 'Руководство',
  'API Reference': 'Справочник API',
  'On this page': 'На этой странице',
  'Back to top': 'Наверх',
  'Search': 'Поиск',
  'Search documentation': 'Поиск по документации',
  'Launch Map': 'Открыть карту',
  'Docs': 'Документация',
  'Open Source · MIT': 'Открытый код · MIT',
  'MIT Licensed': 'Лицензия MIT',
  'Report an issue': 'Сообщить об ошибке',
  'GitHub repository': 'Репозиторий GitHub',
  'Toggle navigation': 'Показать меню',
  'Copied': 'Скопировано',
  'Copy to clipboard': 'Скопировать',
  'Copy': 'Копировать',
  'Note': 'Примечание',
  'Caution': 'Внимание',
  'Tip': 'Совет',
  'Send request': 'Отправить запрос',
  'Loading…': 'Загрузка…',
  'Parameters': 'Параметры',
  'Returns': 'Возвращает',
  'Example response': 'Пример ответа',
  'Try it': 'Попробовать',
  'Response': 'Ответ',
  'No parameters': 'Параметров нет',
  'Request failed': 'Запрос не выполнен',
  '← Previous': '← Назад',
  'Next →': 'Далее →',
  'Endpoints': 'Эндпоинтов',
  'Live feeds': 'Живых лент',
  'Keys required': 'Ключей требуется',
  'endpoint, no key\n              required.': 'эндпоинт, ключи не требуются.',
  // Разделы руководства
  'Overview': 'Обзор',
  'Quick Start': 'Быстрый старт',
  'Self-Hosting': 'Самостоятельный хостинг',
  'Configuration': 'Конфигурация',
  'Interface Guide': 'Руководство по интерфейсу',
  'OI & MCP': 'OI и MCP',
  'Keyboard Shortcuts': 'Горячие клавиши',
  'Conventions': 'Соглашения',
  // Группы API
  'System': 'Система',
  'Aviation & Space': 'Авиация и космос',
  'Earth & Environment': 'Земля и окружающая среда',
  'Geopolitical': 'Геополитика',
  'Media & Markets': 'Медиа и рынки',
  'Surveillance & Infrastructure': 'Наблюдение и инфраструктура',
  'Cyber Threat': 'Киберугрозы',
  'OSINT Toolkit': 'Инструменты OSINT',
  'Recon Scanner': 'RECON-сканер',
  'Entity Graph': 'Граф сущностей',
  'AI Analysis': 'Анализ на ИИ',
  'OI (Assist & Prediction)': 'OI (ассистент и прогнозирование)',
  'Polybolos SDK': 'SDK Polybolos',
  'Webhooks': 'Вебхуки',
  // Панель навигации и разделы руководства (дополнительно)
  'Build on the': 'Стройте на',
  'OSIRIS platform': 'платформе OSIRIS',
  'endpoints, no key required.': 'эндпоинтов, ключи не требуются.',
  'Read by the application': 'Читается приложением',
  'Optional — higher rate limits only': 'Опционально — только для повышенных лимитов',
  'No credentials needed': 'Учётные данные не нужны',
  'Try before you write code': 'Попробуйте, прежде чем писать код',
  'Secrets hygiene': 'Гигиена секретов',
  'Responsible use': 'Ответственное использование',
  'How long a prediction takes': 'Сколько занимает прогноз',
  'Fetch live aircraft': 'Запрос живых самолётов',
  'Aggregate counters': 'Сводные счётчики',
  'Passive subdomain enumeration': 'Пассивный перебор поддоменов',
  'Local development': 'Локальная разработка',
  'Build and test': 'Сборка и тесты',
  'Predict over the REST API': 'Прогноз через REST API',
  'Connect an agent': 'Подключите агента',
  // Карточки интерфейса
  'Layer Panel': 'Панель слоёв',
  'RECON Toolkit': 'Инструменты RECON',
  'Intel Feed': 'Лента разведданных',
  'Region Dossier': 'Досье региона',
  'Status Bar': 'Строка состояния',
  'The left rail. Switches individual feeds on and off, and carries the theme selector.': 'Левая панель. Включает и выключает отдельные ленты, здесь же выбор темы.',
  'DNS, WHOIS, certificate transparency, IP and ASN enrichment, breach checks, sanctions, CVE lookup, port scanning.': 'DNS, WHOIS, прозрачность сертификатов, данные IP и ASN, проверка утечек, санкции, поиск CVE, сканирование портов.',
  'A running stream of incoming events across every enabled feed.': 'Поток входящих событий по всем включённым лентам.',
  'Double right-click the map for a composite summary of that location from every feed covering it.': 'Двойной правый клик по карте — сводка по локациям из всех покрывающих их лент.',
  'Link analysis, expanding one node at a time into its neighbours.': 'Анализ связей: раскрытие одного узла за раз к его соседям.',
  'Community and docs links on the left, then a live ticker of prices and significant seismic events.': 'Слева ссылки на сообщество и документацию, затем живой тикер цен и значимых сейсмических событий.',
  // Карточки OI
  'Your own key': 'Ваш собственный ключ',
  'Cost': 'Стоимость',
  'Sharing': 'Публикация',
  'Steering': 'Управление',
  'On the globe': 'На глобусе',
  'Workspace': 'Рабочее пространство',
  'Research': 'Исследование',
  'Prices': 'Цены',
  'What it rests on': 'На чём основан',
  'Every level': 'Каждый уровень',
  'Its record': 'Его история',
  'Sources': 'Источники',
  'Answers': 'Ответы',
  // Горячие клавиши
  'Toggle fullscreen': 'Полноэкранный режим',
  'Share current view': 'Поделиться текущим видом',
  'Toggle layer panel': 'Панель слоёв',
  'Toggle markets panel': 'Панель рынков',
  'Toggle intel feed': 'Лента разведданных',
  'Reset to global view': 'Сброс к мировому обзору',
  'Show help': 'Показать помощь',
  'Close panels / popups': 'Закрыть панели / попапы',
  // Соглашения API
  'Errors': 'Ошибки',
  'Caching': 'Кэширование',
  'Rate limits': 'Лимиты запросов',
  'Timestamps': 'Метки времени',
  // Каталог API — раздел «Земля и окружающая среда» (эндпоинт /api/sentinel)
  'Sentinel satellite imagery scenes covering a point.':
    'Сцены спутниковых снимков Sentinel, покрывающие точку.',
  'Latitude of the point of interest.': 'Широта интересующей точки.',
  'Longitude of the point of interest.': 'Долгота интересующей точки.',
  'Search radius in kilometres.': 'Радиус поиска в километрах.',
  'How far back to search, in days.': 'Глубина поиска в архиве, в днях.',
};
export function ru(s?: string | null): string {
  if (!s) return s as any;
  const t = String(s).trim();
  return RU[t] ?? t;
}
